In [4]:
import nidaqmx
from numpy import *

In [ ]:
# from Hugh's scripts

waveform = [list(waveform[::2]),list(waveform[1::2])]
def create_task():
    task = nidaqmx.Task()
    task.ao_channels.add_ao_voltage_chan(" /%s/ao1, /%s/ao0" % ( args.device, args.device), min_val=0, max_val=5)
  #  task.ao_channels.add_ao_voltage_chan(" ", min_val=0, max_val=5)
    task.timing.cfg_samp_clk_timing(rate=RATE, samps_per_chan=len(waveform[0]), sample_mode = nidaqmx.constants.AcquisitionType.FINITE)
    task.write(waveform, timeout=10, auto_start=False)
    return task
    
def run_task(task):
    task.start()
    task.wait_until_done()
    task.stop()
    
output_wave =  create_task()



In [5]:
DEV = "dev0"
CHAN_MOD = "ao0"
CHAN_CLK = "ao1"


RATE = 100
VON = 3.3
NCLOCK = int(.01 * RATE) # clocked at 100 Hz
VMODMAX = 1.
VMODMIN = 0

In [23]:
# create a bit sequence from a string to output
text = "hello world"
text = frombuffer(text.encode(), dtype='uint8')
textbits = unpackbits(text)
textbits

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0], dtype=uint8)

In [26]:
# differential phase shift
# using units of pi
dphi = .5
dpsk_signal = zeros_like(textbits, dtype=float)
for i in range(1, len(textbits)):
    dpsk_signal[i] = dpsk_signal[i - 1] + dphi*textbits[i]
dpsk_signal = dpsk_signal % 2
dpsk_signal

array([ 0. ,  0.5,  1. ,  1. ,  1.5,  1.5,  1.5,  1.5,  1.5,  0. ,  0.5,
        0.5,  0.5,  1. ,  1. ,  1.5,  1.5,  0. ,  0.5,  0.5,  1. ,  1.5,
        1.5,  1.5,  1.5,  0. ,  0.5,  0.5,  1. ,  1.5,  1.5,  1.5,  1.5,
        0. ,  0.5,  0.5,  1. ,  1.5,  0. ,  0.5,  0.5,  0.5,  1. ,  1. ,
        1. ,  1. ,  1. ,  1. ,  1. ,  1.5,  0. ,  0.5,  0.5,  1. ,  1.5,
        0. ,  0. ,  0.5,  1. ,  1. ,  1.5,  0. ,  0.5,  1. ,  1. ,  1.5,
        0. ,  0.5,  0.5,  0.5,  1. ,  1. ,  1. ,  1.5,  0. ,  0. ,  0.5,
        1. ,  1. ,  1. ,  1. ,  1.5,  0. ,  0. ,  0. ,  0.5,  0.5,  0.5])

In [24]:


# create a waveform for output to nidaq
wave_mod = repeat(textbits, 2)*VMODMAX

wave_clk = (arange(len(wave1), dtype=float) % 2) * VON
wave_mod, wave_clk

(array([ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,
         1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
         0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
         1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
         0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
         1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,
         1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
         0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,
         0.,  1.,  1.,  0.,  0.,  0.,  0.]),
 array

In [ ]:
# create and configure nidaq task

task = nidaqmx.Task()

task.ao_channels.add_ao_voltage_chan(
    "/%s/%s, /%s/%s" % (DEV, CHAN_MOD, DEV, CHAN_CLK), 
    min_val=-1, 
    max_val=5)

task.timing.cfg_samp_clk_timing(
    rate=RATE*2, 
    samps_per_chan=len(wave1), 
    sample_mode=nidaqmx.constants.AcquisitionType.CONTINUOUS)

task.write([wave1, wave2], timeout=10, auto_start=False)

In [21]:
# run nidaq task

task.start()

# task.stop()

NameError: name 'task' is not defined

In [ ]:
task.stop()